import type { Metadata } from "next";
import SessionProviderWrapper from "../components/SessionProviderWrapper";
import "./globals.css";

const geistSans = undefined;
const geistMono = undefined;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
